---
 - name: Install Elk
   hosts: elk
   become: true
   tasks:

   - name: set vm.max_map_count to 262144 in sysctl
     sysctl: 
       name: vm.max_map_count
       value: '262144'

   - name: docker.io
     apt:
       force_apt_get: yes
       update_cache: yes
       name: docker.io
       state: present

   - name: Install pip3
     apt:
       force_apt_get: yes
       name: python3-pip
       state: present

   - name: Install Docker python module
     pip:
       name: docker
       state: present

   - name: Docker sebp Elk v761
     docker_container:
       name: elk
       image: sebp/elk:761
       published_ports: 5601:5601, 9200:9200, 5044:5044

   - name: Enabled docker service
     systemd:
       name: docker
       enabled: yes
